name: push

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Another step"